Panic in main: runtime error: slice bounds out of range [362:0]

Time: 2025-08-25T14:05:22-04:00

Stack Trace:
goroutine 1 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.25.0/x64/src/runtime/debug/stack.go:26 +0x64
github.com/charmbracelet/crush/internal/log.RecoverPanic({0x101e41d4e, 0x4}, 0x102a608c0)
	/home/runner/work/crush/crush/internal/log/log.go:62 +0x1b8
panic({0x102910620?, 0x140030276c8?})
	/opt/hostedtoolcache/go/1.25.0/x64/src/runtime/panic.go:783 +0x120
github.com/charmbracelet/crush/internal/app.(*App).RunNonInteractive(0x14001f7e000, {0x102a8e1f8, 0x140002294c0}, {0x14003b26000, 0x313f}, 0x0)
	/home/runner/work/crush/crush/internal/app/app.go:186 +0xaec
github.com/charmbracelet/crush/internal/cmd.init.func3(0x103a32da0, {0x0, 0x0, 0x0})
	/home/runner/work/crush/crush/internal/cmd/run.go:52 +0x1ec
github.com/spf13/cobra.(*Command).execute(0x103a32da0, {0x103aa4d40, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1015 +0x7d4
github.com/spf13/cobra.(*Command).ExecuteC(0x103a32ae0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1148 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1071
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1064
github.com/charmbracelet/fang.Execute({0x102a8d9a0, 0x103aa4d40}, 0x103a32ae0, {0x1400059dec8, 0x2, 0xd?})
	/home/runner/go/pkg/mod/github.com/charmbracelet/fang@v0.3.1-0.20250711140230-d5ebb8c1d674/fang.go:169 +0x2c4
github.com/charmbracelet/crush/internal/cmd.Execute()
	/home/runner/work/crush/crush/internal/cmd/root.go:88 +0xbc
main.main()
	/home/runner/work/crush/crush/main.go:30 +0x68

